AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Purple service app for multi-bus, multi-account-pattern

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Handler: app.lambda_handler
    Runtime: python3.8
    Tags:
      pattern: multi-bus-multi-account-pattern

Parameters:
  EventBusName:
    Description: Name of the purple service app event bus
    Type: String
    Default: purple-service-event-bus-multi-bus

  BlueServiceEventBusArn:
    Description: ARN of the Blue service event bus to add rules
    Type: String

  BlueServiceAccountNo:
    Description: Account Id Blue service event bus to add rules
    Type: String

  OrangeServiceEventBusArn:
    Description: ARN of the Orange service event bus to add rules
    Type: String

  OrangeServiceAccountNo:
    Description: Account Id Orange service event bus to add rules
    Type: String

Resources:

  # Event bus for purple service.
  PurpleServiceEventBus: 
    Type: AWS::Events::EventBus
    Properties: 
        Name: !Ref EventBusName
      
  # Resource policy for Purple service event bus
  PurpleServicePublishStatement:
    Type: AWS::Events::EventBusPolicy
    Properties:
      EventBusName: !Ref PurpleServiceEventBus
      StatementId: "PurpleServicePublish"
      Statement:
        Effect: "Allow"
        Principal:
          AWS: 
            - !Sub arn:aws:iam::${AWS::AccountId}:root
        Action: "events:PutEvents"
        Resource: !GetAtt PurpleServiceEventBus.Arn
        Condition:
          StringEquals:
            "events:source": ["com.exampleCorp.PurpleService"]

  PurpleEventBusRuleCreationStatement:
    Type: AWS::Events::EventBusPolicy
    Properties:
      EventBusName: !Ref PurpleServiceEventBus
      StatementId: "AllServiceRuleCreation"
      Statement:
        Effect: "Allow"
        Principal:
          AWS: 
            - !Sub arn:aws:iam::${BlueServiceAccountNo}:root
            - !Sub arn:aws:iam::${OrangeServiceAccountNo}:root
        Action:
          - "events:PutRule"
          - "events:DeleteRule"
          - "events:DescribeRule"
          - "events:DisableRule"
          - "events:EnableRule"
          - "events:PutTargets"
          - "events:RemoveTargets"
        Resource:
          - !Sub arn:aws:events:${AWS::Region}:${AWS::AccountId}:rule/${PurpleServiceEventBus.Name}/*
        Condition:
          StringEqualsIfExists:
            "events:creatorAccount": "${aws:PrincipalAccount}"
            "events:source": "com.exampleCorp.PurpleService"

  PurpleServicePublisherE2:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: purple_p_e2/
      Policies:
        - Version: '2012-10-17' 
          Statement:
            - Effect: Allow
              Action:
                - events:PutEvents
              Resource: "*" 
      Environment:
        Variables:
          EVENT_BUS_ARN: !Ref PurpleServiceEventBus

  PurpleServiceSubscriberE1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: purple_s_e1/
      Events:
        PurpleE1Rule:
          Type: EventBridgeRule
          Properties:
            EventBusName: !Ref PurpleServiceEventBus
            Pattern:
              source:
                - com.exampleCorp.BlueService
              detail-type:
                - Event1

  PurpleServiceSubscriberE3:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: purple_s_e3/
      Events:
        PurpleE3Rule:
          Type: EventBridgeRule
          Properties:
            EventBusName: !Ref PurpleServiceEventBus
            Pattern:
              source:
                - com.exampleCorp.PurpleService
              detail-type:
                - Event3

  # Rule that is placed on the Purple event bus for Event 1
  PurpleServiceE1SubscriptionRule:
    Type: AWS::Events::Rule
    Properties:
      Name: PurpleE1Subscription
      Description: Cross account rule created by Purple service for event 1
      EventBusName: !Ref BlueServiceEventBusArn # ARN of the blue event bus
      EventPattern:
        source:
          - com.exampleCorp.BlueService
        detail-type:
          - Event1
      State: ENABLED
      Targets: 
        - Id: SendEvent1ToPurpleServiceEventBus
          Arn: !GetAtt PurpleServiceEventBus.Arn
          RoleArn: !GetAtt ServiceEventBusToPurpleServiceEventBusRole.Arn
          DeadLetterConfig:
            Arn: !GetAtt PurpleServiceEventBusDlq.Arn

  # Rule that is placed on the DevOps event bus for Event 2
  PurpleServiceE3SubscriptionRule:
    Type: AWS::Events::Rule
    Properties:
      Name: PurpleE3Subscription
      Description: Cross account rule created by Blue service for event 2
      EventBusName: !Ref OrangeServiceEventBusArn # ARN of the orange event bus
      EventPattern:
        source:
          - com.exampleCorp.OrangeService
        detail-type:
          - Event3
      State: ENABLED
      Targets: 
        - Id: SendEvent3ToPurpleServiceEventBus
          Arn: !GetAtt PurpleServiceEventBus.Arn
          RoleArn: !GetAtt ServiceEventBusToPurpleServiceEventBusRole.Arn
          DeadLetterConfig:
            Arn: !GetAtt PurpleServiceEventBusDlq.Arn

  # This IAM role allows EventBridge to assume the permissions necessary to send events 
  # from the DevOps event bus to the Blue service event bus. No resource policy is required
  # on the Blue service event bus.
  ServiceEventBusToPurpleServiceEventBusRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - events.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:   
        - PolicyName: PutEventsOnPurpleServiceEventBus
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 'events:PutEvents'
                Resource: !GetAtt PurpleServiceEventBus.Arn

  # Blue service event bus targe DLQ 
  PurpleServiceEventBusDlq:
    Type: AWS::SQS::Queue

  # SQS resource policy required to allow targets on service buses to send failed messages to target DLQ
  PurpleServiceEventBusDlqPolicy: 
    Type: AWS::SQS::QueuePolicy
    Properties: 
      Queues: 
        - !Ref PurpleServiceEventBusDlq
      PolicyDocument: 
        Statement: 
          - Action: 
              - "SQS:SendMessage" 
            Effect: "Allow"
            Resource: !GetAtt PurpleServiceEventBusDlq.Arn
            Principal:  
              Service: "events.amazonaws.com"
            Condition:
              ArnEquals:
                "aws:SourceArn": [
                  !GetAtt PurpleServiceE1SubscriptionRule.Arn, 
                  !GetAtt PurpleServiceE3SubscriptionRule.Arn
                ]

Outputs:
  PurpleServiceEventBusArn:
    Description: The ARN of the Purple event bus
    Value: !GetAtt PurpleServiceEventBus.Arn
  PurpleServicePublisherE2:
    Description: Lambda function ARN for purple service publishing event 2
    Value: !GetAtt PurpleServicePublisherE2.Arn
  PurpleServiceSubscriberE1:
    Description: Lambda function ARN for purple service subscriber to event 1
    Value: !GetAtt PurpleServiceSubscriberE1.Arn
  PurpleServiceSubscriberE3:
    Description: Lambda function ARN for purple service subscriber to event 3
    Value: !GetAtt PurpleServiceSubscriberE3.Arn
  PurpleE1Subscription:
    Description: Rule ARN for purple service event 1 subscription
    Value: !GetAtt PurpleServiceE1SubscriptionRule.Arn
  PurpleE3Subscription:
    Description: Rule ARN for purple service event 3 subscription
    Value: !GetAtt PurpleServiceE3SubscriptionRule.Arn